[package]
name = "bug_report"
version = "0.1.0"
authors = ["Dávid Kosztka <dkosztka@bol.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = "= 0.1.8"
tower-service = "= 0.3.1"